### This workflow setup instance then build and push images ###
name: Multi-arch build 

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify release tag (ex. 7.0.0)'
        type: string
        required: true
      test-repo:
        type: boolean
        description: 'Push to test repo? Specify tag with rc (ex. 7.0.0-rc25)'
        default: true
      docs-community:
        type: boolean
        description: 'Build Docs-Community?'
        default: true
      docs-enterprise:
        type: boolean
        description: 'Build Docs-Enterprise?'
        default: true
      docs-developer:
        type: boolean
        description: 'Build Docs-Developer?'
        default: true
      docs-non-plugins:
        type: boolean
        description: 'Build Docs-non-plugins?'
        default: true
      docs-utils:
        type: boolean
        description: 'Build Docs-utils?'
        default: true
      docs-balancer:
        type: boolean
        description: 'Build Docs-balancer?'
        default: true
      
jobs:
  prepare-build:
    name: "Prepare build"
    runs-on: ubuntu-latest
    outputs:
      sourceTag: ${{ steps.prepare.outputs.sourceTag }}
      dsHash: ${{ steps.prepare.outputs.dsHash }}
      docker-username: ${{ steps.prepare.outputs.docker-username }}
      docker-usertoken: ${{ steps.prepare.outputs.docker-usertoken }}
    steps:
      - name: prepare-build
        id: prepare
        shell: bash
        run: |
            ### Specify docker credentials ###
            if ! ${{ github.event.inputs.test-repo }}; then
               echo "PROD REPO SPECIFYED>>>>>>>>>>"
               docker-username=${{ secrets.DOCKER_PROD_USERNAME }}
               docker-usertoken=${{ secrets.DOCKER_PROD_USERTOKEN }}
            elif ${{ github.event.inputs.test-repo }}; then
               echo "TEST REPO SPECIFYED>>>>>>>>>>"
               docker-username=${{ secrets.DOCKER_TEST_USERNAME }}value
               docker-usertoken=${{ secrets.DOCKER_TEST_USERTOKEN }}value
            fi
             
            echo "sourceTag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
            echo "dsHash=$(echo -n "$(date +'%Y.%m.%d-%H%M')" | md5sum | awk '{print $1}')" >> "$GITHUB_OUTPUT"
            echo "docker-username=${docker-username}" >> "$GITHUB_OUTPUT"
            echo "docker-usertoken=${docker-usertoken}" >> $GITHUB_OUTPUT"

  build:
    name: "${{ matrix.name }}"
    runs-on: ubuntu-latest
    needs: [prepare-build]
    strategy:
      fail-fast: false
      matrix:
        include:
          - edition: ""
            name: "Build Docs Community Edition"
            dockerfile: "Dockerfile"
            images: "proxy docservice converter"

          - edition: "-ee"
            name: "Build Docs Enterprise Edition"
            dockerfile: "Dockerfile"
            images: "proxy docservice converter"

          - edition: "-de"
            name: "Build Docs Developer Edition"
            dockerfile: "Dockerfile"
            images: "proxy docservice converter"
                      
          - edition: "-de"
            name: "Build Docs Developer Edition non-plugins"
            dockerfile: "Dockerfile.noplugins"
            images: "proxy docservice converter"
            postfix: "-noplugins"

          - edition: ""
            name: "Build utils"
            dockerfile: "Dockerfile"
            images: "example utils"

          - edition: ""
            name: "Build balancer"
            dockerfile: "Dockerfile.balancer"
            images: "balancer"
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ github.event.outputs.docker-username }}
      #    password: ${{ github.event.outputs.docker-usertoken }}

      - name: "Build Docs${{ matrix.edition }}"
        env:
           DS_VERSION_HASH: ${{ needs.prepare-build.outputs.dsHash }}
           SOURCE_TAG: ${{ needs.prepare-build.outputs.sourceTag }}
           NOPLUG_POSTFIX: ${{ matrix.postfix }}
           DOCKERFILE: ${{ matrix.dockerfile }}
        run: |
          : ${DS_VERSION_HASH:?Should be set!}

          DS_VERSION_HASH=${DS_VERSION_HASH} \
          DOCKER_TAG=$(echo ${SOURCE_TAG} | sed 's/^.//') \
          PRODUCT_EDITION=${{ matrix.edition }} \
          TAG=$DOCKER_TAG \
            docker buildx bake \
            -f docker-bake.hcl ${{ matrix.images }} \
            --print
